vendor_name = "Example 1"

[identity]
vendor_id = 123
product_code = 8000
revision_number = 1

[pdos]
num_rpdo = 4
num_tpdo = 4

[[objects]]
index = 0x2000
parameter_name = "Measurement"
object_type = "var"
access_type = "ro"
data_type = "uint16"

[[objects]]
index = 0x2001
parameter_name = "Misc"
object_type = "record"
[[objects.subs]]
sub_index = 1
parameter_name = "first"
field_name = "field_a"
data_type = "uint16"
access_type = "rw"
[[objects.subs]]
sub_index = 2
parameter_name = "first"
field_name = "field_b"
data_type = "uint16"
access_type = "rw"
[[objects.subs]]
sub_index = 3
parameter_name = "first"
field_name = "field_c"
data_type = "uint16"
access_type = "rw"