[package]
name = "integration_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
canopen-common = { path = "../canopen-common" }
canopen-node = { version = "0.1.0", path = "../canopen-node", features = ["log"] }
canopen-client = { version = "0.1.0", path = "../canopen-client" }
critical-section = { version = "*", features = ["std"] }
futures = "*"
