[package]
name = "zencan-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Local
zencan-common.workspace = true
zencan-macro.workspace = true

# External
critical-section.workspace = true
defmt-or-log = { version = "0.2.0", default-features = false }
futures.workspace = true
log = { version = "0.4" }

[features]
default = ["log", "std"]
std = ["critical-section/std", "zencan-common/std"]
log = ["defmt-or-log/log"]
defmt = ["defmt-or-log/defmt"]
socketcan = ["zencan-common/socketcan", "std"]

[profile.test]
default = ["log", "std"]