[package]
name = "zencan-eds"
version = "0.1.0"
edition = "2021"

[dependencies]
configparser = "3.1"
snafu.workspace = true

zencan-common = { path = "../zencan-common" }

[dev-dependencies]
tempfile = "*"