[package]
name = "eds-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
configparser = "3.1"
snafu = "0.8"

zencan-common = { path = "../zencan-common" }

[dev-dependencies]
tempfile = "*"