[package]
name = "zencan-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
critical-section = "1.1"
crossbeam = { version = "0.8", default-features=false }
lazy_static = "1.5"

[features]
default = ["std"]
std = ["critical-section/std"]