[package]
name = "zencan-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
critical-section.workspace = true
crossbeam.workspace = true
int-enum = "1.2.0"
snafu.workspace = true
socketcan = { workspace = true, optional = true }

[features]
default = ["socketcan", "std"]
std = ["critical-section/std", "snafu/std"]
socketcan = ["dep:socketcan", "std",]
