[package]
name = "zencan-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
critical-section.workspace = true
crossbeam.workspace = true
snafu.workspace = true

[features]
default = ["std"]
std = ["critical-section/std"]