name: Rust Checks

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --examples --verbose
    - name: Clippy
      run: cargo clippy --examples -- -D warnings
    - name: Run tests
      run: cargo test --verbose